# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaregiverScheduler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'RxSwift'
              target.build_configurations.each do |config|
                  if config.name == 'Debug'
                      config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                  end
              end
          end
      end
  end

  # Pods for CaregiverScheduler

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  pod 'Action'
  
  # Data persitence
  pod 'Disk', '~> 0.3.3'
  
  # Networking
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'Kingfisher', '~> 4.0'

  # UI
  pod 'SwiftSpinner'

  target 'CaregiverSchedulerTests' do
    inherit! :search_paths
    # Pods for testing

   pod 'Moya/RxSwift', '~> 11.0'
   pod 'RxBlocking', '~> 4.0'
   pod 'RxTest',     '~> 4.0'

  end


end
